#define windowName_conf "Tetris CSFML" // Window name
#define UIBGCOLOR sfColor_fromRGB(26, 26, 26) // Field background
#define UIFGINACTIVECOLOR sfColor_fromRGB(55, 59, 65) // Field inactive cell outline
#define UIFGACTIVECOLOR sfColor_fromRGB(40, 42, 46) // Field active cell outline
#define LCOLOR sfColor_fromRGB(222, 147, 95) // Orange color of L shape
#define RLCOLOR sfColor_fromRGB(95, 129, 157)
#define SCOLOR sfColor_fromRGB(140, 148, 64)
#define ZCOLOR sfColor_fromRGB(165, 66, 66)
#define BCOLOR sfColor_fromRGB(197, 200, 198)
#define ICOLOR sfColor_fromRGB(94, 141, 135)
#define TCOLOR sfColor_fromRGB(133, 103, 143)
#define moveRepeatLatency1 150000 // microseconds, only for left-right arrows,
                  // first repeat move when long push
#define moveRepeatLatency2  30000 // microseconds, for Left, Right and Down
                  // arrows, the rest repeat move when long push
#define basicLatency 500000
#define PUT_LATENCY 300000
#define RM_LINE_SCORE 100
#define LEVELUP_SCORE 100


/*
 * 19..........
 * 18..........
 * 17..........
 * 16..........
 * 15..........
 * 14..........
 * 13..........
 * 12..........
 * 11..........
 * 10..........
 *  9..........
 *  8..........
 *  7..........
 *  6..........
 *  5.......#..
 *  4......##..
 *  3......#...
 *  2.#.##.....
 *  1.##.#..#..
 *  0..#.#.###.
 *   0123456789
 *
 *  L
 *  ..#. .#.. .... ##..
 *  ###. .#.. ###. .#..
 *  .... .##. #... .#..
 *  .... .... .... ....
 *
 *  RL
 *  #... .##. .... .#..
 *  ###. .#.. ###. .#..
 *  .... .#.. ..#. ##..
 *  .... .... .... ....
 *
 *  Z
 *  ##.. ..#. .... .#..
 *  .##. .##. ##.. ##..
 *  .... .#.. .##. #...
 *  .... .... .... ....
 *
 *  S
 *  .##. .#.. .... #...
 *  ##.. .##. .##. ##..
 *  .... ..#. ##.. .#..
 *  .... .... .... ....
 *
 *  Brick
 *  ##.. ##.. ##.. ##..
 *  ##.. ##.. ##.. ##..
 *  .... .... .... ....
 *  .... .... .... ....
 *
 *  I
 *  .#.. .... .#.. ....
 *  .#.. #### .#.. ####
 *  .#.. .... .#.. ....
 *  .#.. .... .#.. ....
 *
 *  T
 *  .#.. .#.. .... .#..
 *  ###. .##. ###. ##..
 *  .... .#.. .#.. .#..
 *  .... .... .... ....
 */

