#define windowName_conf "SFML" // Window name
#define uiColor1 sfColor_fromRGB(0, 0, 0) // Field background
#define uiColor2 sfColor_fromRGB(80, 80, 80) // Field cell outline
#define tOrange sfColor_fromRGB(255, 130, 0) // Orange color of L shape
#define tBlue sfColor_fromRGB(0, 0, 255)
#define tGreen sfColor_fromRGB(0, 255, 0)
#define tRed sfColor_fromRGB(255, 0, 0)
#define tYellow sfColor_fromRGB(255, 255, 0)
#define tCyan sfColor_fromRGB(0, 255, 255)
#define tMagneta sfColor_fromRGB(192, 0, 255)
#define moveRepeatLatency1 150000 //microseconds, only for left-right arrows, first repeat move when long push
#define moveRepeatLatency2  30000 //microseconds, for Left, Right and Down arrows, the rest repeat move when long push


/*
 * 19..........
 * 18..........
 * 17..........
 * 16..........
 * 15..........
 * 14..........
 * 13..........
 * 12..........
 * 11..........
 * 10..........
 *  9..........
 *  8..........
 *  7..........
 *  6..........
 *  5.......#..
 *  4......##..
 *  3......#...
 *  2.#.##.....
 *  1.##.#..#..
 *  0..#.#.###.
 *   0123456789
 *   
 *  L
 *  ..#. .#.. .... ##..
 *  ###. .#.. ###. .#..
 *  .... .##. #... .#..
 *  .... .... .... ....
 *
 *  RL
 *  #... .##. .... .#..
 *  ###. .#.. ###. .#..
 *  .... .#.. ..#. ##..
 *  .... .... .... ....
 *
 *  Z
 *  ##.. ..#. .... .#..
 *  .##. .##. ##.. ##..
 *  .... .#.. .##. #...
 *  .... .... .... ....
 *
 *  S
 *  .##. .#.. .... #...
 *  ##.. .##. .##. ##..
 *  .... ..#. ##.. .#..
 *  .... .... .... ....
 *
 *  Brick
 *  ##.. ##.. ##.. ##..
 *  ##.. ##.. ##.. ##..
 *  .... .... .... ....
 *  .... .... .... ....
 *
 *  I
 *  .#.. .... .#.. ....
 *  .#.. #### .#.. ####
 *  .#.. .... .#.. ....
 *  .#.. .... .#.. ....
 *
 *  T
 *  .#.. .#.. .... .#..
 *  ###. .##. ###. ##..
 *  .... .#.. .#.. .#..
 *  .... .... .... ....
 */

